import type { ReliefPreset } from "../types";

export const presets: ReliefPreset[] = [
  {
    id: "synthetic-depth",
    name: "Synthetic Depth",
    description: "Dark monochrome point scan with subtle source texture.",
    params: {
      gridWidth: 560,
      gridHeight: 315,
      depthScale: 2.05,
      depthGamma: 1.52,
      pointSize: 0.28,
      pointOpacity: 0.98,
      colorStrength: 0.12,
      backgroundFade: 0,
      foregroundBoost: 0.2,
      nearThreshold: 0.06,
      farThreshold: 0.78,
      brightness: 2.12,
      textureMix: 0.16,
      temporalSmoothing: 0.8,
      scanReveal: 1,
      trailAmount: 0.01,
      breathing: 0,
      monochrome: true,
    },
  },
  {
    id: "ghost-relief",
    name: "Ghost Relief",
    description: "Soft translucent relief with gentle depth and slow breathing.",
    params: {
      depthScale: 2.5,
      pointSize: 2.8,
      pointOpacity: 0.56,
      colorStrength: 0.42,
      backgroundFade: 0.72,
      foregroundBoost: 0.2,
      nearThreshold: 0,
      farThreshold: 1,
      brightness: 0.85,
      textureMix: 0.22,
      temporalSmoothing: 0.82,
      breathing: 0.14,
      scanReveal: 0.82,
      monochrome: true,
    },
  },
  {
    id: "lidar-scan",
    name: "LiDAR Scan",
    description: "Sharper cyan-green scan styling with foreground emphasis.",
    params: {
      gridWidth: 420,
      gridHeight: 236,
      depthScale: 3.3,
      depthGamma: 1.42,
      pointSize: 0.12,
      pointOpacity: 0.69,
      colorStrength: 1,
      backgroundFade: 0.67,
      foregroundBoost: 0.81,
      nearThreshold: 0.04,
      farThreshold: 0.95,
      brightness: 0.78,
      textureMix: 0.48,
      temporalSmoothing: 0.7,
      inferenceFPS: 20,
      renderScale: 1.25,
      morphAmount: 1,
      morphSpeed: 0.66,
      scanReveal: 1,
      scanDirection: "left-right",
      trailAmount: 0,
      breathing: 0.01,
      depthQuantize: 0,
      glitchAmount: 0.01,
      monochrome: false,
    },
  },
  {
    id: "topographic",
    name: "Topographic",
    description: "Quantized contour-like relief for readable depth bands.",
    params: {
      depthScale: 3,
      pointSize: 2.4,
      pointOpacity: 0.8,
      colorStrength: 0.74,
      backgroundFade: 0.52,
      foregroundBoost: 0.34,
      nearThreshold: 0.03,
      farThreshold: 0.96,
      brightness: 0.84,
      textureMix: 0.36,
      depthQuantize: 9,
      temporalSmoothing: 0.78,
      scanReveal: 1,
    },
  },
  {
    id: "soft-hologram",
    name: "Soft Hologram",
    description: "Airy blue-violet relief for portrait-like material.",
    params: {
      depthScale: 2.2,
      pointSize: 3.1,
      pointOpacity: 0.5,
      colorStrength: 0.34,
      backgroundFade: 0.78,
      foregroundBoost: 0.18,
      nearThreshold: 0,
      farThreshold: 1,
      brightness: 0.9,
      textureMix: 0.18,
      temporalSmoothing: 0.86,
      breathing: 0.2,
      monochrome: true,
    },
  },
  {
    id: "depth-sculpture",
    name: "Depth Sculpture",
    description: "Dense, high-contrast sculptural depth for still captures.",
    params: {
      depthScale: 4.1,
      pointSize: 2,
      pointOpacity: 0.92,
      colorStrength: 0.68,
      backgroundFade: 0.34,
      foregroundBoost: 0.52,
      nearThreshold: 0.05,
      farThreshold: 0.94,
      brightness: 0.88,
      textureMix: 0.28,
      temporalSmoothing: 0.72,
      scanReveal: 1,
    },
  },
  {
    id: "glitch-field",
    name: "Glitch Field",
    description: "Noisier relief with scan artifacts for motion experiments.",
    params: {
      depthScale: 3.7,
      pointSize: 1.9,
      pointOpacity: 0.72,
      colorStrength: 1,
      backgroundFade: 0.44,
      foregroundBoost: 0.46,
      nearThreshold: 0.08,
      farThreshold: 0.92,
      brightness: 0.72,
      textureMix: 0.42,
      temporalSmoothing: 0.52,
      scanReveal: 0.64,
      glitchAmount: 0.18,
      trailAmount: 0.18,
    },
  },
];

export const initialPresetId = "lidar-scan";

export function findPreset(id: string): ReliefPreset {
  return presets.find((preset) => preset.id === id) ?? presets[0]!;
}
